export const dynamic = "force-dynamic"
export const revalidate = 0

export async function POST(request: Request) {
  try {
    const { prompt } = await request.json()

    if (!prompt || prompt.trim().length === 0) {
      return Response.json({ error: "Prompt is required" }, { status: 400 })
    }

    try {
      const apiKey = process.env.OPENAI_API_KEY
      if (!apiKey) {
        throw new Error("OPENAI_API_KEY not set")
      }

      const openAiResponse = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${apiKey}`,
        },
        cache: "no-store",
        // @ts-ignore - Next.js runtime specific fetch option
        next: { revalidate: 0 },
        body: JSON.stringify({
          model: "gpt-4o-mini",
          temperature: 0.4,
          top_p: 0.9,
          presence_penalty: 0.3,
          max_tokens: 800,
          messages: [
            {
              role: "system",
              content: [
                "You are an expert project planner.",
                "Return ONLY a valid JSON array of 5-7 phases. No markdown, no backticks, no explanations.",
                'Each item must have: "title" (string), "icon" (an emoji), "description" (string).',
              ].join(" "),
            },
            {
              role: "user",
              content: `Create a detailed roadmap for the project idea below. Tailor phases and descriptions specifically to the idea.\n\nProject idea: ${prompt}\n\nReturn ONLY the JSON array.`,
            },
          ],
        }),
      })

      if (!openAiResponse.ok) {
        const errText = await openAiResponse.text()
        throw new Error(`OpenAI API error: ${openAiResponse.status} ${errText}`)
      }

      const data = await openAiResponse.json()
      let text: string = data?.choices?.[0]?.message?.content ?? ""

      console.log("[v0] Raw response:", text)

      let jsonText = text.trim()

      // Remove markdown code block markers if present
      if (jsonText.includes("```json")) {
        jsonText = jsonText.split("```json")[1].split("```")[0].trim()
      } else if (jsonText.includes("```")) {
        jsonText = jsonText.split("```")[1].split("```")[0].trim()
      }

      // Extract JSON array if wrapped in text/object
      const arrayMatch = jsonText.match(/\[\s*\{[\s\S]*\}\s*\]/)
      if (arrayMatch) {
        jsonText = arrayMatch[0]
      }

      console.log("[v0] Cleaned JSON:", jsonText)

      const phases = JSON.parse(jsonText)

      // Validate that we got an array
      if (!Array.isArray(phases)) {
        throw new Error("Response is not an array")
      }

      return Response.json(
        {
          title: prompt,
          phases: phases.map((phase: any, idx: number) => ({
            id: idx + 1,
            title: phase.title || "Untitled Phase",
            icon: phase.icon || "⭐",
            description: phase.description || "No description provided",
          })),
        },
        { headers: { "Cache-Control": "no-store" } },
      )
    } catch (aiError: any) {
      console.error("[v0] AI Error:", aiError.message)
      return Response.json(
        {
          error: "Upstream generation failed",
          details: aiError?.message ?? "Unknown error",
        },
        { status: 502, headers: { "Cache-Control": "no-store" } },
      )
    }
  } catch (error) {
    console.error("Error generating roadmap:", error)
    return Response.json({ error: "Failed to generate roadmap" }, { status: 500 })
  }
}

// Removed mock fallback; responses are generated by GPT or return an error
